default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sani_development

test:
  <<: *default
  database: sani_test

production:
  <<: *default
  database: sani_production
  username: sani
  password: <%= ENV['SANI_DATABASE_PASSWORD'] %>
